name: Matrix stategy workflow
on: push
jobs:
  job_matrix:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout the code on runner Vm
        uses: actions/checkout@v7
      - name: nstall Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '18'
      - name: instal nodejs dependencies
        run: npm ci
      -name: execute the test cases
        run: npm test 
        
